// this file was generated by id3tagExpHdr; don't edit it

ID3TAG_DEF(id3_file_open,           1)
ID3TAG_DEF(id3_file_close,          2)
ID3TAG_DEF(id3_file_tag,            3)
ID3TAG_DEF(id3_tag_findframe,       4)
ID3TAG_DEF(id3_field_getfullstring, 5)
ID3TAG_DEF(id3_field_getstrings,    6)
ID3TAG_DEF(id3_ucs4_utf16duplicate, 7)
ID3TAG_DEF(id3_ucs4_latin1duplicate, 8)
ID3TAG_DEF(id3_free,                9)

#undef ID3TAG_DEF
