// this file was generated by id3tagExpHdr; don't edit it

typedef struct id3_file *(*pid3_file_open)(char const *, enum id3_file_mode);
typedef int (*pid3_file_close)(struct id3_file *);
typedef struct id3_tag *(*pid3_file_tag)(struct id3_file const *);
typedef struct id3_frame *(*pid3_tag_findframe)(struct id3_tag const *,char const *, unsigned int);
typedef id3_ucs4_t const *(*pid3_field_getfullstring)(union id3_field const *);
typedef id3_ucs4_t const *(*pid3_field_getstrings)(union id3_field const *,unsigned int);
typedef id3_latin1_t *(*pid3_ucs4_latin1duplicate)(id3_ucs4_t const *);
typedef id3_utf16_t *(*pid3_ucs4_utf16duplicate)(id3_ucs4_t const *);
typedef void (*pid3_free)(void *);	
