// this file was generated by samplerateExpHdr; don't edit it

typedef SRC_STATE* (*psrc_new) (int converter_type, int channels, int *error) ;
typedef SRC_STATE* (*psrc_delete) (SRC_STATE *state) ;
typedef int (*psrc_process) (SRC_STATE *state, SRC_DATA *data) ;
typedef const char* (*psrc_strerror) (int error) ;
typedef void (*psrc_short_to_float_array) (const short *in, float *out, int len) ;
typedef void (*psrc_float_to_short_array) (const float *in, short *out, int len) ;
typedef void (*psrc_int_to_float_array) (const int *in, float *out, int len) ;
typedef void (*psrc_float_to_int_array) (const float *in, int *out, int len) ;
