// this file was generated by samplerateExpHdr; don't edit it

SAMPLERATE_DEF(src_new,                         1)
SAMPLERATE_DEF(src_delete,                      2)
SAMPLERATE_DEF(src_process,                     20)
SAMPLERATE_DEF(src_strerror,                    31)
SAMPLERATE_DEF(src_short_to_float_array,        70)
SAMPLERATE_DEF(src_float_to_short_array,        71)
SAMPLERATE_DEF(src_int_to_float_array,          80)
SAMPLERATE_DEF(src_float_to_int_array,          81)

#undef SAMPLERATE_DEF
