// Copyleft 2013 Chris Korda
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 2 of the License, or any later version.
/*
        chris korda
 
		revision history:
		rev		date	comments
		00		16apr13	initial version
		01		01may13	add record dialog
		02		22may13	add record options and sweep dialog
		03		19jul13	add plugins
		04		03aug13	add metadata

        map resource IDs to help IDs
 
*/

{ID_APP_ABOUT,					IDH_Help_menu_About},
{ID_APP_CHECK_FOR_UPDATES,		IDH_Options_View_Automatically_check_for_updates},
{ID_APP_EXIT,					IDH_File_menu_Exit},
{ID_APP_HOME_PAGE,				IDH_Help_menu_WaveShop_on_the_Web},
{ID_AUDIO_AMPLIFY,				IDH_Audio_menu_Amplify},
{ID_AUDIO_CHANGE_FORMAT,		IDH_Audio_menu_Format},
{ID_AUDIO_EXTRACT_CHANNELS,		IDH_Audio_menu_Extract},
{ID_AUDIO_FADE,					IDH_Audio_menu_Fade},
{ID_AUDIO_FIND_CLIPPING,		IDH_Audio_menu_Find_Clipping},
{ID_AUDIO_GENERATE,				IDH_Audio_menu_Generate},
{ID_AUDIO_INSERT_CHANNEL,		IDH_Audio_menu_Insert_Channel},
{ID_AUDIO_INVERT,				IDH_Audio_menu_Invert},
{ID_AUDIO_NORMALIZE,			IDH_Audio_menu_Normalize},
{ID_AUDIO_PEAK_STATS,			IDH_Audio_menu_Peak_Statistics},
{ID_AUDIO_RESAMPLE,				IDH_Audio_menu_Resample},
{ID_AUDIO_REVERSE,				IDH_Audio_menu_Reverse},
{ID_AUDIO_RMS_STATS,			IDH_Audio_menu_RMS_Statistics},
{ID_AUDIO_SPEAKERS,				IDH_Audio_menu_Speakers},
{ID_AUDIO_SPECTRUM,				IDH_Audio_menu_Spectrum},
{ID_AUDIO_SWAP_CHANNELS,		IDH_Audio_menu_Swap_Channels},
{ID_EDIT_BEGIN_SELECTION,		IDH_Navigation_Selecting_audio},
{ID_EDIT_COPY,					IDH_Edit_menu_Copy},
{ID_EDIT_CUT,					IDH_Edit_menu_Cut},
{ID_EDIT_DELETE,				IDH_Edit_menu_Delete},
{ID_EDIT_DESELECT,				IDH_Navigation_Selecting_audio},
{ID_EDIT_END_SELECTION,			IDH_Navigation_Selecting_audio},
{ID_EDIT_FIND,					IDH_Edit_menu_Find_Find_Next},
{ID_EDIT_FIND_NEXT,				IDH_Edit_menu_Find_Find_Next},
{ID_EDIT_FIND_ZERO_CROSSING,	IDH_Edit_menu_Find_Zero_Crossing},
{ID_EDIT_GOTO_FIRST_FRAME,		IDH_Navigation_Audio_cursor},
{ID_EDIT_GOTO_LAST_FRAME,		IDH_Navigation_Audio_cursor},
{ID_EDIT_GOTO_NOW,				IDH_Navigation_Scrolling},
{ID_EDIT_GOTO_SEL_END,			IDH_Navigation_Scrolling},
{ID_EDIT_GOTO_SEL_START,		IDH_Navigation_Scrolling},
{ID_EDIT_INSERT,				IDH_Edit_menu_Insert},
{ID_EDIT_INSERT_SILENCE,		IDH_Edit_menu_Insert_Silence},
{ID_EDIT_OPTIONS,				IDH_Options_View_Zoom_step_size},
{ID_EDIT_PASTE,					IDH_Edit_menu_Paste},
{ID_EDIT_REDO,					IDH_Edit_menu_Undo_Redo},
{ID_EDIT_SELECT_ALL,			IDH_Navigation_Selecting_audio},
{ID_EDIT_UNDO,					IDH_Edit_menu_Undo_Redo},
{ID_FILE_CLOSE,					IDH_File_menu_Close},
{ID_FILE_EXPORT,				IDH_File_menu_Export},
{ID_FILE_INFO,					IDH_File_menu_File_Info},
{ID_FILE_NEW,					IDH_File_menu_New},
{ID_FILE_OPEN,					IDH_File_menu_Open},
{ID_FILE_SAVE,					IDH_File_menu_Save},
{ID_FILE_SAVE_AS,				IDH_File_menu_Save_As},
{ID_HELP_FINDER,				IDH_Help_menu_Help_topics},
{ID_TRANSPORT_LOOP,				IDH_Transport_menu_Loop},
{ID_TRANSPORT_PAUSE,			IDH_Transport_menu_Play_Pause},
{ID_TRANSPORT_PLAY,				IDH_Transport_menu_Play_Pause},
{ID_TRANSPORT_RECORD,			IDH_Transport_menu_Record},
{ID_TRANSPORT_REWIND,			IDH_Transport_menu_Rewind},
{ID_TRANSPORT_STOP,				IDH_Transport_menu_Stop},
{ID_VIEW_CHANNEL_BAR,			IDH_View_menu_Channel_bar},
{ID_VIEW_CTX_DELETE_CHANNEL,	IDH_Audio_menu_Delete_Channel},
{ID_VIEW_CTX_END_SELECTION,		IDH_Navigation_Selecting_audio},
{ID_VIEW_CTX_INSERT_CHANNEL,	IDH_Audio_menu_Insert_Channel},
{ID_VIEW_CTX_MAXIMIZE_CHANNEL,	IDH_Navigation_Channel_height},
{ID_VIEW_CTX_PASTE,				IDH_Edit_menu_Paste},
{ID_VIEW_CTX_START_SELECTION,	IDH_Navigation_Selecting_audio},
{ID_VIEW_CTX_ZOOM_IN,			IDH_View_menu_Zoom_In},
{ID_VIEW_CTX_ZOOM_OUT,			IDH_View_menu_Zoom_Out},
{ID_VIEW_FIT_VERTICALLY,		IDH_View_menu_Fit_Vertically},
{ID_VIEW_FIT_WINDOW,			IDH_View_menu_Fit_in_Window},
{ID_VIEW_HISTORY_BAR,			IDH_View_menu_History_bar},
{ID_VIEW_METER_BAR,				IDH_View_menu_Meter_bar},
{ID_VIEW_NAVIGATION_BAR,		IDH_View_menu_Navigation_bar},
{ID_VIEW_PITCH_BAR,				IDH_View_menu_Pitch_bar},
{ID_VIEW_RESULTS_BAR,			IDH_View_menu_Results_bar},
{ID_VIEW_SPECTRUM_BAR,			IDH_View_menu_Spectrum_bar},
{ID_VIEW_TRANSPORT_BAR,			IDH_View_menu_Transport_bar},
{ID_VIEW_VOLUME_BAR,			IDH_View_menu_Volume_bar},
{ID_VIEW_ZOOM_IN,				IDH_View_menu_Zoom_In},
{ID_VIEW_ZOOM_OUT,				IDH_View_menu_Zoom_Out},
{ID_WINDOW_ARRANGE,				IDH_Window_menu_Arrange_Icons},
{ID_WINDOW_CASCADE,				IDH_Window_menu_Cascade},
{ID_WINDOW_NEW,					IDH_Window_menu_New_Window},
{ID_WINDOW_TILE_HORZ,			IDH_Window_menu_Tile_Horizontally},
{ID_WINDOW_TILE_VERT,			IDH_Window_menu_Tile_Vertically},
{IDD_AMPLIFY, 					IDH_Audio_menu_Amplify},
{IDD_CHANGE_FORMAT,				IDH_Audio_menu_Format},
{IDD_EXPORT,					IDH_File_menu_Export},
{IDD_FADE,						IDH_Audio_menu_Fade},
{IDD_FIND,						IDH_Edit_menu_Find_Find_Next},
{IDD_FIND_CLIPPING,				IDH_Audio_menu_Find_Clipping},
{IDD_INSERT_SILENCE,			IDH_Edit_menu_Insert_Silence},
{IDD_METADATA, 					IDH_Edit_menu_Metadata},
{IDD_MISSING_LIBRARY, 			IDH_Loose_ends_MP3_encoding},
{IDD_MP3_ENCODER, 				IDH_Loose_ends_MP3_encoding},
{IDD_NORMALIZE,					IDH_Audio_menu_Normalize},
{IDD_OPT_AUDIO,					IDH_Options_Audio_Playback_device},
{IDD_OPT_EDIT,					IDH_Options_Edit_Undo_levels},
{IDD_OPT_RECORD,				IDH_Options_Record_Activation},
{IDD_OPT_RTSA,					IDH_Options_Spectrum_Window_function},
{IDD_OPT_VIEW,					IDH_Options_View_Zoom_step_size},
{IDD_PEAK_STATS,				IDH_Audio_menu_Peak_Statistics},
{IDD_PLUGIN_PARAM,				IDH_Plugin_menu_Plugins},
{IDD_RECORD,					IDH_Transport_menu_Record},
{IDD_RESAMPLE,					IDH_Audio_menu_Resample},
{IDD_RMS_STATS,					IDH_Audio_menu_RMS_Statistics},
{IDD_SPEAKERS,					IDH_Audio_menu_Speakers},
{IDD_SPECTRUM,					IDH_Audio_menu_Spectrum},
{IDD_SWAP_CHANNELS,				IDH_Audio_menu_Swap_Channels},
{IDD_SWEEP,						IDH_Audio_menu_Generate},
{IDD_VIEW_COLORS, 				IDH_Options_View_Colors},
{IDD_WAVE_GEN,					IDH_Audio_menu_Generate},
{IDD_WAVE_GEN_OSC,				IDH_Audio_menu_Generate},
{MAKEBARID(CMainFrame::CBI_NAV),		IDH_View_menu_Navigation_bar},
{MAKEBARID(CMainFrame::CBI_PITCH),		IDH_View_menu_Pitch_bar},
{MAKEBARID(CMainFrame::CBI_VOLUME),		IDH_View_menu_Volume_bar},
{MAKEBARID(CMainFrame::CBI_HISTORY),	IDH_View_menu_History_bar},
{MAKEBARID(CMainFrame::CBI_RESULTS),	IDH_View_menu_Results_bar},
{IDC_VOLUME_MUTE,				IDH_View_menu_Volume_bar},
{IDC_NAV_SHOW_LENGTH,			IDH_View_menu_Navigation_bar},