#define IDH_Getting_Started_Introduction 1
#define IDH_Getting_Started_License 2
#define IDH_Getting_Started_Requirements 3
#define IDH_Getting_Started_Installing 4
#define IDH_Getting_Started_Uninstalling 5
#define IDH_Getting_Started_Getting_help 6
#define IDH_Navigation_Audio_cursor 7
#define IDH_Navigation_Time_format 8
#define IDH_Navigation_Zooming_time 9
#define IDH_Navigation_Zooming_amplitude 10
#define IDH_Navigation_Scrolling 11
#define IDH_Navigation_Selecting_audio 12
#define IDH_Navigation_Channel_height 13
#define IDH_Navigation_Channel_selection 14
#define IDH_File_menu_New 15
#define IDH_File_menu_Open 16
#define IDH_File_menu_Close 17
#define IDH_File_menu_Save 18
#define IDH_File_menu_Save_As 19
#define IDH_File_menu_File_Info 20
#define IDH_File_menu_Export 21
#define IDH_File_menu_Exit 22
#define IDH_Edit_menu_Undo_Redo 23
#define IDH_Edit_menu_Clipboard 24
#define IDH_Edit_menu_Cut 25
#define IDH_Edit_menu_Copy 26
#define IDH_Edit_menu_Paste 27
#define IDH_Edit_menu_Insert 28
#define IDH_Edit_menu_Insert_Silence 29
#define IDH_Edit_menu_Delete 30
#define IDH_Edit_menu_Goto 31
#define IDH_Edit_menu_Find_Find_Next 32
#define IDH_Edit_menu_Find_Zero_Crossing 33
#define IDH_Edit_menu_Metadata 34
#define IDH_Transport_menu_Play_Pause 35
#define IDH_Transport_menu_Stop 36
#define IDH_Transport_menu_Rewind 37
#define IDH_Transport_menu_Loop 38
#define IDH_Transport_menu_Record 39
#define IDH_Audio_menu_Amplify 40
#define IDH_Audio_menu_Delete_Channel 41
#define IDH_Audio_menu_Extract 42
#define IDH_Audio_menu_Fade 43
#define IDH_Audio_menu_Find_Clipping 44
#define IDH_Audio_menu_Format 45
#define IDH_Audio_menu_Generate 46
#define IDH_Audio_menu_Insert_Channel 47
#define IDH_Audio_menu_Invert 48
#define IDH_Audio_menu_Normalize 49
#define IDH_Audio_menu_Peak_Statistics 50
#define IDH_Audio_menu_Resample 51
#define IDH_Audio_menu_Reverse 52
#define IDH_Audio_menu_RMS_Statistics 53
#define IDH_Audio_menu_Speakers 54
#define IDH_Audio_menu_Spectrum 55
#define IDH_Audio_menu_Swap_Channels 56
#define IDH_Plugin_menu_Plugins 57
#define IDH_Plugin_menu_Plugins_and_channels 58
#define IDH_Plugin_menu_Getting_more_plugins 59
#define IDH_View_menu_Toolbar 60
#define IDH_View_menu_Status_bar 61
#define IDH_View_menu_Transport_bar 62
#define IDH_View_menu_Navigation_bar 63
#define IDH_View_menu_Volume_bar 64
#define IDH_View_menu_Pitch_bar 65
#define IDH_View_menu_Results_bar 66
#define IDH_View_menu_History_bar 67
#define IDH_View_menu_Meter_bar 68
#define IDH_View_menu_Spectrum_bar 69
#define IDH_View_menu_Channel_bar 70
#define IDH_View_menu_Zoom_In 71
#define IDH_View_menu_Zoom_Out 72
#define IDH_View_menu_Fit_in_Window 73
#define IDH_View_menu_Fit_Vertically 74
#define IDH_Window_menu_New_Window 75
#define IDH_Window_menu_Cascade 76
#define IDH_Window_menu_Tile_Horizontally 77
#define IDH_Window_menu_Tile_Vertically 78
#define IDH_Window_menu_Arrange_Icons 79
#define IDH_Window_menu_Window_menu 80
#define IDH_Help_menu_Help_topics 81
#define IDH_Help_menu_WaveShop_on_the_Web 82
#define IDH_Help_menu_Check_for_updates 83
#define IDH_Help_menu_About 84
#define IDH_Options_View_Zoom_step_size 85
#define IDH_Options_View_Show_time_in_sample_frames 86
#define IDH_Options_View_Vertically_sync_channels 87
#define IDH_Options_View_Vertical_zoom_at_cursor 88
#define IDH_Options_View_Highlight_interpolation 89
#define IDH_Options_View_Show_channel_names 90
#define IDH_Options_View_Automatically_check_for_updates 91
#define IDH_Options_View_Max_density 92
#define IDH_Options_View_Colors 93
#define IDH_Options_Edit_Undo_levels 94
#define IDH_Options_Edit_Disk_threshold 95
#define IDH_Options_Edit_Temporary_files_location 96
#define IDH_Options_Audio_Playback_device 97
#define IDH_Options_Audio_Playback_buffer_size 98
#define IDH_Options_Audio_Record_device 99
#define IDH_Options_Audio_Record_buffer_size 100
#define IDH_Options_Audio_MP3_import 101
#define IDH_Options_Audio_AAC_MP4_import 102
#define IDH_Options_Audio_VBR_encoding_quality 103
#define IDH_Options_Audio_Meter_clip_threshold 104
#define IDH_Options_Spectrum_Window_function 105
#define IDH_Options_Spectrum_Window_size 106
#define IDH_Options_Spectrum_Averaging 107
#define IDH_Options_Spectrum_Plot_style 108
#define IDH_Options_Spectrum_Frequency_axis 109
#define IDH_Options_Spectrum_Channel_mode 110
#define IDH_Options_Spectrum_Plot_colors 111
#define IDH_Options_Spectrum_Show_peaks 112
#define IDH_Options_Spectrum_Peak_hold 113
#define IDH_Options_Spectrum_Peak_decay 114
#define IDH_Options_Record_Activation 115
#define IDH_Options_Record_Audio_format 116
#define IDH_Options_Record_Hot_keys 117
#define IDH_Options_Record_Output_folder 118
#define IDH_Options_Record_Triggers 119
#define IDH_Loose_ends_Performance 120
#define IDH_Loose_ends_Bit_perfect 121
#define IDH_Loose_ends_MP3_encoding 122
#define IDH_Loose_ends_File_formats 123
#define IDH_Loose_ends_Shortcuts 124
