// this file was generated by madExpHdr; don't edit it

MAD_DEF(mad_decoder_init,        1)
MAD_DEF(mad_decoder_run,         2)
MAD_DEF(mad_decoder_finish,      3)
MAD_DEF(mad_stream_buffer,       6)
MAD_DEF(mad_stream_errorstr,     9)

#undef MAD_DEF
