// this file was generated by madExpHdr; don't edit it

typedef void (*pmad_stream_buffer)(struct mad_stream *, unsigned char const *, unsigned long);
typedef char const *(*pmad_stream_errorstr)(struct mad_stream const *);
typedef void (*pmad_decoder_init)(struct mad_decoder *, void *, enum mad_flow (*)(void *, struct mad_stream *), enum mad_flow (*)(void *, struct mad_header const *), enum mad_flow (*)(void *, struct mad_stream const *, struct mad_frame *), enum mad_flow (*)(void *, struct mad_header const *, struct mad_pcm *), enum mad_flow (*)(void *, struct mad_stream *, struct mad_frame *), enum mad_flow (*)(void *, void *, unsigned int *));
typedef int (*pmad_decoder_finish)(struct mad_decoder *);
typedef int (*pmad_decoder_run)(struct mad_decoder *, enum mad_decoder_mode);
