//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WaveShop.rc
//
#define IDR_MAINFRAME                   101
#define IDR_PEAK_STATS_CTX              102
#define IDR_RTSA_CTX                    103
#define IDR_TRANSPORT                   104
#define IDR_VIEW_CTX                    105
#define IDR_WAVVIETYPE                  106
#define IDB_HEADER_SORT                 107
#define IDB_HISTORY_POS                 108
#define IDI_MUTE_DOWN                   109
#define IDI_MUTE_UP                     110
#define IDI_NAV_SHOW_LENGTH             111
#define IDD_ABOUTBOX                    112
#define IDD_AMPLIFY                     113
#define IDD_CHANGE_FORMAT               114
#define IDD_EXPORT                      115
#define IDD_FADE                        116
#define IDD_FILE_SEARCH_DLG             117
#define IDD_FIND                        118
#define IDD_FIND_CLIPPING               119
#define IDD_INSERT_SILENCE              120
#define IDD_METADATA                    121
#define IDD_MISSING_LIBRARY             122
#define IDD_MP3_ENCODER                 123
#define IDD_NAV_BAR                     124
#define IDD_NORMALIZE                   125
#define IDD_OPT_AUDIO                   126
#define IDD_OPT_EDIT                    127
#define IDD_OPT_RECORD                  128
#define IDD_OPT_RTSA                    129
#define IDD_OPT_VIEW                    130
#define IDD_PEAK_STATS                  131
#define IDD_PITCH_BAR                   132
#define IDD_PLUGIN_PARAM                133
#define IDD_PROGRESS                    134
#define IDD_PROGRESS_DUAL               135
#define IDD_PROGRESS_SLAVE              136
#define IDD_RECORD                      137
#define IDD_RESAMPLE                    138
#define IDD_RMS_STATS                   139
#define IDD_SPEAKERS                    140
#define IDD_SPECTRUM                    141
#define IDD_SWAP_CHANNELS               142
#define IDD_SWEEP                       143
#define IDD_VIEW_COLORS                 144
#define IDD_VOLUME_BAR                  145
#define IDD_WAVE_GEN                    146
#define IDD_WAVE_GEN_OSC                147
#define IDS_AMPL_CLIP_WARN              200
#define IDS_AMPL_NO_GAIN                201
#define IDS_APP_ABOUT_TEXT              202
#define IDS_APP_CANT_INIT_COM           203
#define IDS_APP_FOLDER_NOT_FOUND        204
#define IDS_APP_FOLDER_REQUIRED         205
#define IDS_APP_HELP_FILE_MISSING       206
#define IDS_APP_LICENSE                 207
#define IDS_APP_TEMP_FOLDER_NOT_FOUND   208
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    209
#define IDS_CKUP_CANT_GET_ADDR          210
#define IDS_CKUP_CANT_LOAD_DLL          211
#define IDS_CLIP_COL_CHANNEL            212
#define IDS_CLIP_COL_LENGTH             213
#define IDS_CLIP_COL_START              214
#define IDS_CLOBBER_CHECK               215
#define IDS_DDV_VALUE_GT_ZERO           216
#define IDS_DIRECTSOUND_ERROR           217
#define IDS_DLL_CANT_GET_FUNCTION       218
#define IDS_DOC_ENCODING                219
#define IDS_DOC_INSERTING               220
#define IDS_DOC_READING                 221
#define IDS_DOC_WRITING                 222
#define IDS_DS_CAPTURE_OVERRUN          223
#define IDS_EDIT_REDO_FMT               224
#define IDS_EDIT_UNDO_FMT               225
#define IDS_EXPO_ENDIAN_DEFAULT         226
#define IDS_EXPO_ENDIAN_FORCE_BIG       227
#define IDS_EXPO_ENDIAN_FORCE_CPU       228
#define IDS_EXPO_ENDIAN_FORCE_LITTLE    229
#define IDS_FILE_EXPORT_AS              230
#define IDS_FILE_INFO                   231
#define IDS_FILT_AUDIO_FILES            232
#define IDS_FILT_WAVE_FILES             233
#define IDS_FIND_ALL_CHANNELS           234
#define IDS_FIND_MATCH_NOT_FOUND        235
#define IDS_HISTORY_BAR                 236
#define IDS_HIST_COL_ACTION             237
#define IDS_HIST_INITIAL_STATE          238
#define IDS_HIST_REDOING                239
#define IDS_HIST_UNDOING                240
#define IDS_HLINK_CANT_LAUNCH           241
#define IDS_INS_BAD_LENGTH              242
#define IDS_LAME_ERR_ENCODE             243
#define IDS_LAME_ERR_ENC_BUFFER_SIZE    244
#define IDS_LAME_ERR_ENC_INIT_PARAMS    245
#define IDS_LAME_ERR_ENC_MALLOC         246
#define IDS_LAME_ERR_ENC_PSYCHO         247
#define IDS_LAME_ERR_INIT               248
#define IDS_LAME_ERR_INIT_PARAMS        249
#define IDS_LAME_ERR_SET_AVG_BIT_RATE   250
#define IDS_LAME_ERR_SET_BIT_RATE       251
#define IDS_LAME_ERR_SET_ENC_QUALITY    252
#define IDS_LAME_ERR_SET_NUM_CHANNELS   253
#define IDS_LAME_ERR_SET_NUM_SAMPLES    254
#define IDS_LAME_ERR_SET_SAMPLE_RATE    255
#define IDS_LAME_ERR_SET_VBR_MODE       256
#define IDS_LAME_ERR_SET_VBR_QUALITY    257
#define IDS_MAIN_CANT_CREATE_PROCESS    258
#define IDS_MAIN_CANT_MAKE_WAVE         259
#define IDS_MAIN_DESTINATION_FOLDER     260
#define IDS_MAIN_GENERATING_AUDIO       261
#define IDS_METADATA_ALBUM              262
#define IDS_METADATA_ARTIST             263
#define IDS_METADATA_COL_NAME           264
#define IDS_METADATA_COL_VALUE          265
#define IDS_METADATA_COMMENT            266
#define IDS_METADATA_COPYRIGHT          267
#define IDS_METADATA_DATE               268
#define IDS_METADATA_GENRE              269
#define IDS_METADATA_LICENSE            270
#define IDS_METADATA_SOFTWARE           271
#define IDS_METADATA_TITLE              272
#define IDS_METADATA_TRACKNUMBER        273
#define IDS_METER_BAR                   274
#define IDS_MISSLIB_BROWSE_FILTER       275
#define IDS_MISSLIB_CANT_GET_VERSION    276
#define IDS_MISSLIB_NOT_FOUND           277
#define IDS_MISSLIB_PATH_CHECK          278
#define IDS_MISSLIB_VERSION_TOO_OLD     279
#define IDS_MP4AD_ERRORS                280
#define IDS_MP4AD_EXCESS_ERRORS         281
#define IDS_OPTIONS                     282
#define IDS_OPT_RESET_ALL               283
#define IDS_OPT_RESTORE_DEFAULTS        284
#define IDS_OPT_SELECT_RECORD_FOLDER    285
#define IDS_OPT_SELECT_TEMP_FOLDER      286
#define IDS_OSC_PULSE                   287
#define IDS_OSC_RAMP_DOWN               288
#define IDS_OSC_RAMP_UP                 289
#define IDS_OSC_RANDOM                  290
#define IDS_OSC_RANDOM_RAMP             291
#define IDS_OSC_SINE                    292
#define IDS_OSC_SQUARE                  293
#define IDS_OSC_TRIANGLE                294
#define IDS_PKST_COL_BIAS_PCT           295
#define IDS_PKST_COL_CHANNEL            296
#define IDS_PKST_COL_DC_BIAS            297
#define IDS_PKST_COL_MAX_PCT            298
#define IDS_PKST_COL_MAX_SAMPLE         299
#define IDS_PKST_COL_MIN_PCT            300
#define IDS_PKST_COL_MIN_SAMPLE         301
#define IDS_PKST_COL_PEAK_DB            302
#define IDS_PLUGIN_ABOUT                303
#define IDS_PLUGIN_APPLYING             304
#define IDS_PLUGIN_BROKEN               305
#define IDS_PLUGIN_CANT_CREATE_VIEW     306
#define IDS_PLUGIN_CANT_INSTANTIATE     307
#define IDS_PLUGIN_CANT_LOAD            308
#define IDS_PLUGIN_CHANNEL_MISMATCH     309
#define IDS_PLUGIN_REPEAT               310
#define IDS_REC_CANT_CHANGE_DEVICE      311
#define IDS_REC_FILTER                  312
#define IDS_REC_PAUSE_CHECK             313
#define IDS_REC_SAVE_AS                 314
#define IDS_REC_STATUS_PAUSE            315
#define IDS_REC_STATUS_RECORD           316
#define IDS_REC_STATUS_STOP             317
#define IDS_REC_STOP_CHECK              318
#define IDS_REC_UNSAVED_CHANGES         319
#define IDS_REC_UNTITLED                320
#define IDS_REC_WAIT_ERROR              321
#define IDS_REC_WAIT_TIMEOUT            322
#define IDS_RESAMP_CHANGE_RATE          323
#define IDS_RESULTS_BAR                 324
#define IDS_RMS_COL_AVG                 325
#define IDS_RMS_COL_CHANNEL             326
#define IDS_RMS_COL_MAX                 327
#define IDS_RMS_COL_MIN                 328
#define IDS_RMS_COL_TOTAL               329
#define IDS_RMS_TAB_HISTOGRAM           330
#define IDS_RMS_TAB_STATS               331
#define IDS_SFEX_TOO_MANY_FRAMES        332
#define IDS_SPECTRUM_BAR                333
#define IDS_SPKR_BACK_CENTER            334
#define IDS_SPKR_BACK_LEFT              335
#define IDS_SPKR_BACK_RIGHT             336
#define IDS_SPKR_CHANNEL_MISMATCH       337
#define IDS_SPKR_FRONT_CENTER           338
#define IDS_SPKR_FRONT_LEFT             339
#define IDS_SPKR_FRONT_LEFT_OF_CENTER   340
#define IDS_SPKR_FRONT_RIGHT            341
#define IDS_SPKR_FRONT_RIGHT_OF_CENTER  342
#define IDS_SPKR_LEFT                   343
#define IDS_SPKR_LOW_FREQUENCY          344
#define IDS_SPKR_MONO                   345
#define IDS_SPKR_RIGHT                  346
#define IDS_SPKR_SIDE_LEFT              347
#define IDS_SPKR_SIDE_RIGHT             348
#define IDS_SPKR_STEREO                 349
#define IDS_SPKR_TOP_BACK_CENTER        350
#define IDS_SPKR_TOP_BACK_LEFT          351
#define IDS_SPKR_TOP_BACK_RIGHT         352
#define IDS_SPKR_TOP_CENTER             353
#define IDS_SPKR_TOP_FRONT_CENTER       354
#define IDS_SPKR_TOP_FRONT_LEFT         355
#define IDS_SPKR_TOP_FRONT_RIGHT        356
#define IDS_TEXT_FILTER                 357
#define IDS_TOOLBAR                     358
#define IDS_TRANSPORT                   359
#define IDS_UC_AMPLIFY                  360
#define IDS_UC_CHANGE_FORMAT            361
#define IDS_UC_CUT                      362
#define IDS_UC_DELETE                   363
#define IDS_UC_DELETE_CHANNEL           364
#define IDS_UC_FADE                     365
#define IDS_UC_INSERT                   366
#define IDS_UC_INSERT_CHANNEL           367
#define IDS_UC_INSERT_SILENCE           368
#define IDS_UC_INVERT                   369
#define IDS_UC_METADATA                 370
#define IDS_UC_NORMALIZE                371
#define IDS_UC_PASTE                    372
#define IDS_UC_PLUGIN                   373
#define IDS_UC_RESAMPLE                 374
#define IDS_UC_REVERSE                  375
#define IDS_UC_SPEAKERS                 376
#define IDS_UC_SWAP_CHANNELS            377
#define IDS_UNIT_SAMPLE_FRAMES          378
#define IDS_UNIT_SECONDS                379
#define IDS_VIEW_CANT_COPY              380
#define IDS_VIEW_CANT_CUT               381
#define IDS_VIEW_CANT_DELETE            382
#define IDS_VIEW_CANT_INSERT            383
#define IDS_VIEW_CANT_PASTE             384
#define IDS_WAVE_ERR_BAD_BIT_COUNT      385
#define IDS_WAVE_ERR_BAD_BLOCK_ALIGN    386
#define IDS_WAVE_ERR_BAD_CHANNEL_COUNT  387
#define IDS_WAVE_ERR_BAD_FORMAT_SIZE    388
#define IDS_WAVE_ERR_BAD_SAMPLE_RATE    389
#define IDS_WAVE_ERR_END_OF_FILE        390
#define IDS_WAVE_ERR_NOT_RIFF           391
#define IDS_WAVE_ERR_NOT_WAVE           392
#define IDS_WAVE_ERR_NO_DATA_CHUNK      393
#define IDS_WAVE_ERR_NO_FORMAT_CHUNK    394
#define IDS_WAVE_ERR_UNKNOWN_FORMAT     395
#define IDS_WEDT_FMT_CHANNEL_COUNT      396
#define IDS_WEDT_FMT_SAMPLE_BITS        397
#define IDS_WEDT_FMT_SAMPLE_RATE        398
#define IDS_WEDT_FORMAT_MISMATCH        399
#define IDS_WEDT_INCOMPATIBLE_FORMATS   400
#define IDS_WEDT_INVALID_WAVE           401
#define IDS_WEDT_NOT_IN_MEMORY          402
#define IDS_WEDT_NO_TEMP_FILE_NAME      403
#define IDS_WEDT_RANGE_ERROR            404
#define IDS_WEDT_SAMPLE_RATE_MISMATCH   405
#define IDS_WEDT_SAMPLE_SIZE_MISMATCH   406
#define IDS_WGEN_OSC_CARRIER            407
#define IDS_WGEN_OSC_MODULATOR          408
#define IDS_WNDFN_BARTLETT              409
#define IDS_WNDFN_BLACKMAN              410
#define IDS_WNDFN_BLACKMAN_HARRIS       411
#define IDS_WNDFN_HAMMING               412
#define IDS_WNDFN_HANN                  413
#define IDS_WNDFN_RECTANGULAR           414
#define IDS_WNDFN_WELCH                 415
#define IDS_WPRO_AMPLIFY                416
#define IDS_WPRO_BAD_CHANNEL            417
#define IDS_WPRO_CHANGE_FORMAT          418
#define IDS_WPRO_COPY_CHANNEL           419
#define IDS_WPRO_DELETE_CHANNEL         420
#define IDS_WPRO_EXTRACT_CHANNELS       421
#define IDS_WPRO_FADE                   422
#define IDS_WPRO_FIND_CLIPPING          423
#define IDS_WPRO_FIND_SAMPLE            424
#define IDS_WPRO_GET_SPECTRUM           425
#define IDS_WPRO_INSERT_CHANNEL         426
#define IDS_WPRO_INVALID_WAVE           427
#define IDS_WPRO_INVERT                 428
#define IDS_WPRO_NORMALIZE              429
#define IDS_WPRO_PEAK_STATS             430
#define IDS_WPRO_RESAMPLE               431
#define IDS_WPRO_REVERSE                432
#define IDS_WPRO_RMS_BAD_PANE_SIZE      433
#define IDS_WPRO_RMS_STATS              434
#define IDS_WPRO_SWAP_CHANNELS          435
#define IDS_WPRO_TOO_FEW_CHANNELS       436
#define IDS_WPRO_TOO_FEW_FRAMES         437
#define IDC_ABOUT_KISS_FFT              1001
#define IDC_ABOUT_LIBFAAD2              1002
#define IDC_ABOUT_LIBMAD                1003
#define IDC_ABOUT_LIBMP3LAME            1004
#define IDC_ABOUT_LIBSAMPLERATE         1005
#define IDC_ABOUT_LIBSNDFILE            1006
#define IDC_ABOUT_LICENSE               1007
#define IDC_ABOUT_TEXT                  1008
#define IDC_ABOUT_URL                   1009
#define IDC_AMPL_CLIP                   1010
#define IDC_AMPL_GAIN                   1011
#define IDC_AMPL_PEAK                   1012
#define IDC_CFMT_CHANNELS               1013
#define IDC_CFMT_SAMPLE_BITS            1014
#define IDC_CFMT_SAMPLE_RATE            1015
#define IDC_EXPO_ENDIANNESS             1016
#define IDC_EXPO_MAJOR_FORMAT           1017
#define IDC_EXPO_SUBTYPE                1018
#define IDC_FADE_END                    1019
#define IDC_FADE_LOG                    1020
#define IDC_FADE_START                  1021
#define IDC_FADE_TYPE                   1022
#define IDC_FADE_TYPE2                  1023
#define IDC_FADE_TYPE3                  1024
#define IDC_FCLIP_CLIPPING_LEVEL        1025
#define IDC_FCLIP_START_THRESHOLD       1026
#define IDC_FCLIP_STOP_THRESHOLD        1027
#define IDC_FILE_SEARCH_CURRENT_PATH    1028
#define IDC_FIND_CHANNEL                1029
#define IDC_FIND_DIR                    1030
#define IDC_FIND_DIR2                   1031
#define IDC_FIND_MATCH                  1032
#define IDC_FIND_MATCH2                 1033
#define IDC_FIND_TARGET_END             1034
#define IDC_FIND_TARGET_START           1035
#define IDC_FIND_UNIT                   1036
#define IDC_FIND_UNIT2                  1037
#define IDC_FIND_UNIT3                  1038
#define IDC_FIND_WRAP                   1039
#define IDC_HISTORY_LIST                1040
#define IDC_INS_LENGTH                  1041
#define IDC_INS_UNIT                    1042
#define IDC_METADATA_CLEAR              1043
#define IDC_METADATA_LIST               1044
#define IDC_MISSLIB_BROWSE              1045
#define IDC_MISSLIB_DESCRIPTION         1046
#define IDC_MISSLIB_DOWNLOAD            1047
#define IDC_MISSLIB_FILE_NAME           1048
#define IDC_MISSLIB_MIN_VERSION         1049
#define IDC_MISSLIB_PLATFORM            1050
#define IDC_MISSLIB_SEARCH              1051
#define IDC_MP3_ALGORITHM_QUALITY       1052
#define IDC_MP3_BIT_RATE_MODE           1053
#define IDC_MP3_BIT_RATE_MODE2          1054
#define IDC_MP3_BIT_RATE_MODE3          1055
#define IDC_MP3_TARGET_BIT_RATE         1056
#define IDC_MP3_TARGET_BIT_RATE_CAP     1057
#define IDC_MP3_TARGET_BIT_RATE_UNIT    1058
#define IDC_MP3_TARGET_QUALITY          1059
#define IDC_MP3_TARGET_QUALITY_BEST     1060
#define IDC_MP3_TARGET_QUALITY_CAP      1061
#define IDC_MP3_TARGET_QUALITY_FASTEST  1062
#define IDC_NAV_NOW                     1063
#define IDC_NAV_SEL_END                 1064
#define IDC_NAV_SEL_START               1065
#define IDC_NAV_SHOW_LENGTH             1066
#define IDC_NORM_INDEPENDENT            1067
#define IDC_NORM_NORMALIZE              1068
#define IDC_NORM_PEAK_LEVEL             1069
#define IDC_NORM_PEAK_LEVEL_CAPTION     1070
#define IDC_NORM_UNBIAS                 1071
#define IDC_OPT_AUDIO_PLAY_BUF_SIZE     1072
#define IDC_OPT_AUDIO_PLAY_DEVICE       1073
#define IDC_OPT_AUDIO_RECORD_BUF_SIZE   1074
#define IDC_OPT_AUDIO_RECORD_DEVICE     1075
#define IDC_OPT_EDIT_DISK_THRESHOLD     1076
#define IDC_OPT_EDIT_TEMP_FOLDER_BROWSE 1077
#define IDC_OPT_EDIT_TEMP_FOLDER_FREE   1078
#define IDC_OPT_EDIT_TEMP_FOLDER_PATH   1079
#define IDC_OPT_EDIT_TEMP_FOLDER_TYPE   1080
#define IDC_OPT_EDIT_TEMP_FOLDER_TYPE2  1081
#define IDC_OPT_EDIT_UNDO_LEVELS        1082
#define IDC_OPT_EDIT_UNDO_UNLIMITED     1083
#define IDC_OPT_METER_CLIP_THRESHOLD    1084
#define IDC_OPT_MP3_IMPORT_QUALITY      1085
#define IDC_OPT_MP4_DOWNMIX             1086
#define IDC_OPT_MP4_IMPORT_QUALITY      1087
#define IDC_OPT_REC_ACTIVATION          1088
#define IDC_OPT_REC_ACTIVATION2         1089
#define IDC_OPT_REC_ACTIVATION3         1090
#define IDC_OPT_REC_CHANNELS            1091
#define IDC_OPT_REC_FOLDER_BROWSE       1092
#define IDC_OPT_REC_FOLDER_EDIT         1093
#define IDC_OPT_REC_HOT_KEY             1094
#define IDC_OPT_REC_HOT_KEY_FUNCTION    1095
#define IDC_OPT_REC_SAMPLE_RATE         1096
#define IDC_OPT_REC_SAMPLE_SIZE         1097
#define IDC_OPT_REC_START_DURATION      1098
#define IDC_OPT_REC_START_LEVEL         1099
#define IDC_OPT_REC_STOP_DURATION       1100
#define IDC_OPT_REC_STOP_LEVEL          1101
#define IDC_OPT_VBR_QUALITY_EDIT        1102
#define IDC_OPT_VBR_QUALITY_SLIDER      1103
#define IDC_OPT_VIEW_CHANNEL_NAMES      1104
#define IDC_OPT_VIEW_CHECK_FOR_UPDATES  1105
#define IDC_OPT_VIEW_COLORS             1106
#define IDC_OPT_VIEW_MAX_DENSITY        1107
#define IDC_OPT_VIEW_SHOW_INTERPOLAT    1108
#define IDC_OPT_VIEW_TIME_IN_FRAMES     1109
#define IDC_OPT_VIEW_VERT_SYNC_CHANS    1110
#define IDC_OPT_VIEW_VERT_ZOOM_CURSOR   1111
#define IDC_OPT_VIEW_ZOOM_STEP_HORZ     1112
#define IDC_OPT_VIEW_ZOOM_STEP_VERT     1113
#define IDC_PEAK_STATS_LIST             1114
#define IDC_PITCH_EDIT                  1115
#define IDC_PITCH_SLIDER                1116
#define IDC_PLUGIN_ABOUT                1117
#define IDC_PLUGIN_RESET                1118
#define IDC_PLUGIN_VIEW                 1119
#define IDC_PROGRESS                    1120
#define IDC_PROGRESS_PERCENT            1121
#define IDC_PROGRESS_SUBCAPTION         1122
#define IDC_PROGRESS_SUBPROGRESS        1123
#define IDC_REC_CANCEL                  1124
#define IDC_REC_CHANNELS                1125
#define IDC_REC_CHANNELS_CAP            1126
#define IDC_REC_ELAPSED                 1127
#define IDC_REC_FREE_DISK_SPACE         1128
#define IDC_REC_METER                   1129
#define IDC_REC_OPEN_RECORDING          1130
#define IDC_REC_PAUSE                   1131
#define IDC_REC_RECORDING_SIZE          1132
#define IDC_REC_RESUME                  1133
#define IDC_REC_SAMPLE_RATE             1134
#define IDC_REC_SAMPLE_RATE_CAP         1135
#define IDC_REC_SAMPLE_SIZE             1136
#define IDC_REC_SAMPLE_SIZE_CAP         1137
#define IDC_REC_START                   1138
#define IDC_REC_STATUS                  1139
#define IDC_REC_STOP                    1140
#define IDC_REC_SYNC_PLAYBACK           1141
#define IDC_RESAMP_QUALITY              1142
#define IDC_RESAMP_SAMPLE_RATE          1143
#define IDC_RMS_ACCOUNT_FOR_DC          1144
#define IDC_RMS_REFRESH                 1145
#define IDC_RMS_STATS_LIST              1146
#define IDC_RMS_STATS_PLOT              1147
#define IDC_RMS_TAB_CTRL                1148
#define IDC_RMS_TOP_CHANNEL             1149
#define IDC_RMS_TOP_CHANNEL_CAP         1150
#define IDC_RMS_WINDOW_SIZE             1151
#define IDC_RMS_WINDOW_SIZE_CAP         1152
#define IDC_RMS_WINDOW_SIZE_UNIT        1153
#define IDC_RMS_ZERO_WAVE               1154
#define IDC_RMS_ZERO_WAVE2              1155
#define IDC_RTSA_AVERAGING_EDIT         1156
#define IDC_RTSA_AVERAGING_SPIN         1157
#define IDC_RTSA_CHANNEL_MODE           1158
#define IDC_RTSA_COLOR_PLOT_BKGND       1159
#define IDC_RTSA_COLOR_PLOT_GRID        1160
#define IDC_RTSA_FREQ_AXIS              1161
#define IDC_RTSA_PEAK_DECAY             1162
#define IDC_RTSA_PEAK_HOLD              1163
#define IDC_RTSA_PLOT_STYLE             1164
#define IDC_RTSA_SHOW_PEAKS             1165
#define IDC_RTSA_WINDOW_FUNC            1166
#define IDC_RTSA_WINDOW_SIZE            1167
#define IDC_SPEC_CHANNEL_MODE           1168
#define IDC_SPEC_CHANNEL_MODE_CAP       1169
#define IDC_SPEC_EXPORT                 1170
#define IDC_SPEC_FREQ_AXIS              1171
#define IDC_SPEC_FREQ_AXIS_CAP          1172
#define IDC_SPEC_FREQ_EDIT_END          1173
#define IDC_SPEC_FREQ_EDIT_END_CAP      1174
#define IDC_SPEC_FREQ_EDIT_START        1175
#define IDC_SPEC_FREQ_EDIT_START_CAP    1176
#define IDC_SPEC_FREQ_RANGE_AUTO        1177
#define IDC_SPEC_FREQ_RANGE_GROUP       1178
#define IDC_SPEC_PLOT                   1179
#define IDC_SPEC_REFRESH                1180
#define IDC_SPEC_VIEW_CHANNEL           1181
#define IDC_SPEC_VIEW_CHANNEL_CAP       1182
#define IDC_SPEC_WINDOW_FUNC            1183
#define IDC_SPEC_WINDOW_FUNC_CAP        1184
#define IDC_SPEC_WINDOW_SIZE            1185
#define IDC_SPEC_WINDOW_SIZE_CAP        1186
#define IDC_SPKR_LIST                   1187
#define IDC_SPKR_RESET                  1188
#define IDC_SWAP_CHANNEL_A              1189
#define IDC_SWAP_CHANNEL_B              1190
#define IDC_SWEEP_DURATION              1191
#define IDC_SWEEP_END_FREQUENCY         1192
#define IDC_SWEEP_START_FREQUENCY       1193
#define IDC_SWEEP_WAVEFORM              1194
#define IDC_TIME_RULER                  1195
#define IDC_TOOL_ZOOM_IN                1196
#define IDC_TOOL_ZOOM_OUT               1197
#define IDC_VOLUME_MUTE                 1198
#define IDC_VOLUME_SLIDER               1199
#define IDC_VWCLR_EXCLUDED_CHAN_BK      1200
#define IDC_VWCLR_EXCLUDED_CHAN_DATA    1201
#define IDC_VWCLR_INTERPOLATION         1202
#define IDC_VWCLR_SELECTED_WAVE_BK      1203
#define IDC_VWCLR_SELECTED_WAVE_DATA    1204
#define IDC_VWCLR_WAVE_BK               1205
#define IDC_VWCLR_WAVE_DATA             1206
#define IDC_WGEN_ATTACK                 1207
#define IDC_WGEN_CHANNELS               1208
#define IDC_WGEN_DC_BIAS                1209
#define IDC_WGEN_DECAY                  1210
#define IDC_WGEN_DURATION               1211
#define IDC_WGEN_FREQUENCY              1212
#define IDC_WGEN_LOG_FADE               1213
#define IDC_WGEN_MOD_DEPTH              1214
#define IDC_WGEN_MOD_TYPE               1215
#define IDC_WGEN_OSC_TAB                1216
#define IDC_WGEN_PHASE                  1217
#define IDC_WGEN_PULSE_WIDTH            1218
#define IDC_WGEN_RESET                  1219
#define IDC_WGEN_SAMPLE_BITS            1220
#define IDC_WGEN_SAMPLE_RATE            1221
#define IDC_WGEN_SWEEP                  1222
#define IDC_WGEN_VOLUME                 1223
#define IDC_WGEN_WAVEFORM               1224
#define ID_APP_CHECK_FOR_UPDATES        32771
#define ID_APP_HOME_PAGE                32772
#define ID_AUDIO_AMPLIFY                32773
#define ID_AUDIO_CHANGE_FORMAT          32774
#define ID_AUDIO_EXTRACT_CHANNELS       32775
#define ID_AUDIO_FADE                   32776
#define ID_AUDIO_FIND_CLIPPING          32777
#define ID_AUDIO_GENERATE               32778
#define ID_AUDIO_INSERT_CHANNEL         32779
#define ID_AUDIO_INVERT                 32780
#define ID_AUDIO_NORMALIZE              32781
#define ID_AUDIO_PEAK_STATS             32782
#define ID_AUDIO_RESAMPLE               32783
#define ID_AUDIO_REVERSE                32784
#define ID_AUDIO_RMS_STATS              32785
#define ID_AUDIO_SPEAKERS               32786
#define ID_AUDIO_SPECTRUM               32787
#define ID_AUDIO_SWAP_CHANNELS          32788
#define ID_EDIT_BEGIN_SELECTION         32789
#define ID_EDIT_DELETE                  32790
#define ID_EDIT_DESELECT                32791
#define ID_EDIT_END_SELECTION           32792
#define ID_EDIT_FIND_NEXT               32793
#define ID_EDIT_FIND_ZERO_CROSSING      32794
#define ID_EDIT_GOTO_FIRST_FRAME        32795
#define ID_EDIT_GOTO_LAST_FRAME         32796
#define ID_EDIT_GOTO_NOW                32797
#define ID_EDIT_GOTO_SEL_END            32798
#define ID_EDIT_GOTO_SEL_START          32799
#define ID_EDIT_INSERT                  32800
#define ID_EDIT_INSERT_SILENCE          32801
#define ID_EDIT_METADATA                32802
#define ID_EDIT_OPTIONS                 32803
#define ID_FILE_EXPORT                  32804
#define ID_FILE_INFO                    32805
#define ID_INDICATOR_CHANNELS           32806
#define ID_INDICATOR_POSITION           32807
#define ID_INDICATOR_SAMPLE_BITS        32808
#define ID_INDICATOR_SAMPLE_RATE        32809
#define ID_PEAK_STATS_GOTO              32810
#define ID_PLUGIN_REPEAT                32811
#define ID_RTSA_AVERAGING               32812
#define ID_RTSA_AVERAGING2              32813
#define ID_RTSA_AVERAGING3              32814
#define ID_RTSA_AVERAGING4              32815
#define ID_RTSA_AVERAGING5              32816
#define ID_RTSA_AVERAGING6              32817
#define ID_RTSA_CHANNEL_MODE            32818
#define ID_RTSA_CHANNEL_MODE2           32819
#define ID_RTSA_FREQ_AXIS               32820
#define ID_RTSA_FREQ_AXIS2              32821
#define ID_RTSA_OPTIONS                 32822
#define ID_RTSA_PLOT_STYLE              32823
#define ID_RTSA_PLOT_STYLE2             32824
#define ID_RTSA_PLOT_STYLE3             32825
#define ID_RTSA_RESET                   32826
#define ID_RTSA_SHOW_PEAKS              32827
#define ID_RTSA_SHOW_PEAKS2             32828
#define ID_RTSA_SHOW_PEAKS3             32829
#define ID_TRANSPORT_LOOP               32830
#define ID_TRANSPORT_PAUSE              32831
#define ID_TRANSPORT_PLAY               32832
#define ID_TRANSPORT_RECORD             32833
#define ID_TRANSPORT_REWIND             32834
#define ID_TRANSPORT_STOP               32835
#define ID_VIEW_CHANNEL_BAR             32836
#define ID_VIEW_CTX_DELETE_CHANNEL      32837
#define ID_VIEW_CTX_END_SELECTION       32838
#define ID_VIEW_CTX_INSERT_CHANNEL      32839
#define ID_VIEW_CTX_MAXIMIZE_CHANNEL    32840
#define ID_VIEW_CTX_PASTE               32841
#define ID_VIEW_CTX_START_SELECTION     32842
#define ID_VIEW_CTX_ZOOM_IN             32843
#define ID_VIEW_CTX_ZOOM_OUT            32844
#define ID_VIEW_FIT_VERTICALLY          32845
#define ID_VIEW_FIT_WINDOW              32846
#define ID_VIEW_HISTORY_BAR             32847
#define ID_VIEW_METER_BAR               32848
#define ID_VIEW_NAVIGATION_BAR          32849
#define ID_VIEW_PITCH_BAR               32850
#define ID_VIEW_REFRESH                 32851
#define ID_VIEW_RESULTS_BAR             32852
#define ID_VIEW_SPECTRUM_BAR            32853
#define ID_VIEW_TRANSPORT_BAR           32854
#define ID_VIEW_VOLUME_BAR              32855
#define ID_VIEW_ZOOM_IN                 32856
#define ID_VIEW_ZOOM_OUT                32857

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        438
#define _APS_NEXT_COMMAND_VALUE         32858
#define _APS_NEXT_CONTROL_VALUE         1225
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
