// this file was generated by sndfileExpHdr; don't edit it

SNDFILE_DEF(sf_command,              1)
SNDFILE_DEF(sf_open,                 2)
SNDFILE_DEF(sf_close,                3)
SNDFILE_DEF(sf_format_check,         11)
SNDFILE_DEF(sf_readf_short,          17)
SNDFILE_DEF(sf_readf_int,            18)
SNDFILE_DEF(sf_writef_short,         33)
SNDFILE_DEF(sf_writef_int,           34)
SNDFILE_DEF(sf_strerror,             50)
SNDFILE_DEF(sf_get_string,           60)
SNDFILE_DEF(sf_set_string,           61)

#undef SNDFILE_DEF
